### PR TITLE
fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.66`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.dependencies:activiti-dependencies 7.0.66 org.activiti.api:activiti-api-dependencies 7.0.59 org.activiti.core.common:activiti-core-common-dependencies 7.0.28 org.activiti.build:activiti-parent 7.0.45

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.common:activiti-cloud-service-common-dependencies 7.0.56

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.dependencies:activiti-dependencies 7.0.67 org.activiti.api:activiti-api-dependencies 7.0.60 org.activiti.core.common:activiti-core-common-dependencies 7.0.29 org.activiti.build:activiti-parent 7.0.45

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.common:activiti-cloud-service-common-dependencies 7.0.57

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.dependencies:activiti-dependencies 7.0.68 org.activiti.api:activiti-api-dependencies 7.0.60 org.activiti.core.common:activiti-core-common-dependencies 7.0.29 org.activiti.build:activiti-parent 7.0.45

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.dependencies:activiti-dependencies 7.0.69 org.activiti.api:activiti-api-dependencies 7.0.60 org.activiti.core.common:activiti-core-common-dependencies 7.0.29 org.activiti.build:activiti-parent 7.0.45

**Comment by ryandawsonuk** [comment]
Replacing this with https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/173

**Pull request closed without merging**
