### PR TITLE
Improve TaskAdminController in runtime-bundle-service #2066

### PR DESCRIPTION
**Pull request by lucianoprea**
- added more methods for TaskAdminController since they are available in activiti-api

refs [#2066](https://github.com/Activiti/Activiti/issues/2066)

**requires** this PR from common to be merged [#83](https://github.com/Activiti/activiti-cloud-service-common/pull/83) first

### CODE REVIEW

**Comment by mteodori** [comment]
@lucianoprea @salaboy I understand there is more work to do, can you guys review together?

**Comment by salaboy** [comment]
@lucianoprea we will not merge this because we found that we need to be more careful when exposing the endpoints. There is nothing wrong with this PR, but when we looked at it we decided to go step by step exposing only what we can test during the first iteration of Activiti Cloud.

**Comment by lucianoprea** [comment]
@salaboy ok, but remember that @mauriziovitale is blocked by this.

**Comment by salaboy** [comment]
@lucianoprea yes.. we are working on it iteratively... if we expose the endpoints as they are exposed in this PR, some of the core checks will be missed and we will end up with an inconsistent API

**Pull request closed without merging**
