### PR TITLE
Make sure claim task ack is false before sending claim message

### PR DESCRIPTION
**Pull request by erdemedeiros**

### CODE REVIEW

**Comment by salaboy** [comment]
@erdemedeiros what is this? can you please have a catch up at some point about this one?

**Comment by erdemedeiros** [comment]
@salaboy this was suppose to fix a random failure on CommandEndpointIT test. The test is doing: claim/release/claim. The ack flag was set to true during the first claim and was not reset in the second one. However, it seems to be not enough as test still failed (task got suspended for some reason).

**Comment by salaboy** [comment]
@erdemedeiros so.. should we close this PR? 
it looks really confusing to me.. maybe the test is missing a syncronization?

**Comment by erdemedeiros** [comment]
This should solve the failure `expected:<[ASSIGN]ED> but was:<[CREAT]ED>`: https://github.com/Activiti/Activiti/issues/2746

**Pull request merged**
